version: "3.1"
services:  
  mariadb:
    image: mariadb:latest
    container_name: deve_mariadb
    working_dir: /var/lib/mysql/
    volumes:
      - ./database/mariadb:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=senha123
      - MYSQL_DATABASE=base_devedores
    ports:
      - "3306:3306"
  webserverl:
    image: nginx:alpine
    container_name: deve_web_server
    working_dir: /application
    volumes:
      - ./application:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
  php-fpm:
    build: docker/php-fpm
    container_name: deve_php
    working_dir: /application
    volumes:
      - ./application:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
      - ./docker/php-fpm/php-fpm.conf:/etc/php-fpm.conf